### PR TITLE
Fix multiple edge deletion

### LINKED ISSUE #429: Fix delete of multiple edges

### PR DESCRIPTION
**Pull request by JeremieLeymarie**
blip blap blop race conditions vrim vram vroum

Close #429

### CODE REVIEW

File: client/src/builder/hooks/use-builder-edges.tsx [hunk 1]
```diff
@@ -4,31 +4,30 @@ import { useErrorToast } from "./use-error-toast";
...
-    const edges = actionToEdgesAdapter(sourceAction, updatedScene.key);
-    // 1. Filter out existing edges from action
-    // 2. Re-add all updated edges
-    setEdges((prev) =>
-      prev.filter((e) => !isEdgeFromAction(e, sourceActionKey)).concat(edges),
-    );
+  const _updateNodeAndEdges = (updatedScene: Scene) => {
+    const node = sceneToNodeAdapter({ scene: updatedScene, story });
+    const edges = sceneToEdgesAdapter(updatedScene);
+    console.log({ edges });
```
Comment (guillaume-th) [inline client/src/builder/hooks/use-builder-edges.tsx]: petit console.log perdu

File: client/src/domains/builder/builder-service.ts [hunk 2]
```diff
@@ -107,34 +107,75 @@ export const _getBuilderService = ({
...
-          const targets = action.targets.filter(
-            (t) => t.sceneKey !== targetSceneKey,
-          );
-          // If only one target remains, set its probability to 100%
-          if (targets.length === 1) {
-            targets[0]!.probability = 100;
+      // 2. Aggregate targets by action by scene to be able to easily produce update statements
+      // This is important because if don't handle updates in bulk by scene the first updates would be overridden by subsequent ones
+      // (because actions are a part of a scene and Dexie doesn't allow to update only part of a nested object)
+      const targetsToRemoveBySceneByAction = connections.reduce<
```
Comment (guillaume-th) [inline client/src/domains/builder/builder-service.ts]: best naming

**Review by guillaume-th — CHANGES_REQUESTED** [review]

**Review by guillaume-th — APPROVED** [review]
